name: CI/CD Pipeline (Python)

on:
  push:
    branches:
      - main   # Trigger only on pushes to the main branch

jobs:
  # 1️⃣ Test Stage
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'   # Use the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest; fi
          
  # 2️⃣ Build Stage
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest

